default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>
  database: <%= Rails.application.secrets.database[:database] %>
  host: <%= Rails.application.secrets.database[:host] %>

test:
  <<: *default
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>
  database: <%= Rails.application.secrets.database[:database] %>
  host: <%= Rails.application.secrets.database[:host] %>

production:
  <<: *default
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>
  database: <%= Rails.application.secrets.database[:database] %>
  host: <%= Rails.application.secrets.database[:host] %>
